version: "3"

services:

  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - secrets/secrets.yml.dec
    environment:
      - LOCAL=True
      - WEB_CONCURRENCY=2
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

  redis:
    build: ./redis
    ports:
      - "6379:6379"

  db:
    build: ./postgres
    restart: always
    env_file:
      - ./postgres/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d local"]
      interval: 5s
      retries: 5
      timeout: 10s
    # volumes:
    #   - db_data:/var/lib/postgresql/data/

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
#    volumes:
#      - ./frontend:/app
    depends_on:
      backend:
        condition: service_started


# volumes:
#   db_data: