version: "3"

services:

  spotify-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - secrets/secrets.yml.dec
    environment:
      - LOCAL=True
      - GUNICORN_RELOAD=True
      - PUBLIC_URL="http://localhost:8080/"
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
        restart: true

  redis:
    build: ./redis
    ports:
      - "6379:6379"

  db:
    build: ./postgres
    restart: always
    env_file:
      - ./postgres/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d local"]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s
    # volumes:
    #   - db_data:/var/lib/postgresql/data/

# volumes:
#   db_data: